### ISSUE TITLE
Installation fail 

### ISSUE THREAD

**Issue by AlecRust** [splash-cli/splash-cli#22]
I get this on Node v8.9.0 or v9.0.0

```sh
sudo npm i -g splash-cli
/Users/alec/.nvm/versions/node/v8.9.0/bin/splash -> /Users/alec/.nvm/versions/node/v8.9.0/lib/node_modules/splash-cli/bin/index.js
npm ERR! path /Users/alec/.nvm/versions/node/v8.9.0/lib/node_modules/splash-cli/pm2 interval.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/alec/.nvm/versions/node/v8.9.0/lib/node_modules/splash-cli/pm2 interval.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by Rawnly** [comment]
Should be fixed, test it please, for me is everything ok wiht node 8.7.0

**Comment by AlecRust** [comment]
## On 9.0.0

```sh
~ » sudo npm install --global splash-cli                                                                                               alec@Alecs-MacBook-Pro
Alias tip: _ npm install --global splash-cli
Password:
/Users/alec/.nvm/versions/node/v9.0.0/bin/splash -> /Users/alec/.nvm/versions/node/v9.0.0/lib/node_modules/splash-cli/bin/index.js

> fsevents@1.1.3 install /Users/alec/.nvm/versions/node/v9.0.0/lib/node_modules/splash-cli/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@9.0.0 (node-v59 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Darwin 17.2.0
gyp ERR! command "/Users/alec/.nvm/versions/node/v9.0.0/bin/node" "/Users/alec/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean"
gyp ERR! cwd /Users/alec/.nvm/versions/node/v9.0.0/lib/node_modules/splash-cli/node_modules/fsevents
gyp ERR! node -v v9.0.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/alec/.nvm/versions/node/v9.0.0/bin/node /Users/alec/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/alec/.nvm/versions/node/v9.0.0/lib/node_modules/splash-cli/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:135:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:224:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:943:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
node-pre-gyp ERR! System Darwin 17.2.0
node-pre-gyp ERR! command "/Users/alec/.nvm/versions/node/v9.0.0/bin/node" "/Users/alec/.nvm/versions/node/v9.0.0/lib/node_modules/splash-cli/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/alec/.nvm/versions/node/v9.0.0/lib/node_modules/splash-cli/node_modules/fsevents
node-pre-gyp ERR! node -v v9.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok
Failed to execute '/Users/alec/.nvm/versions/node/v9.0.0/bin/node /Users/alec/.nvm/versions/node/v9.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/splash-cli/node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ splash-cli@2.7.1
added 449 packages in 31.442s
```

`splash` command then fails with:

```sh
~ » splash                                                                                                                             alec@Alecs-MacBook-Pro
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1184:7)
    at Function.sync (/Users/alec/.nvm/versions/node/v9.0.0/lib/node_modules/splash-cli/node_modules/mkdirp/index.js:68:14)
    at client (/Users/alec/.nvm/versions/node/v9.0.0/lib/node_modules/splash-cli/client.js:98:10)
    at Object.<anonymous> (/Users/alec/.nvm/versions/node/v9.0.0/lib/node_modules/splash-cli/bin/index.js:61:1)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
```

## On 8.9.0

```sh
~ » sudo npm install --global splash-cli                                                                                               alec@Alecs-MacBook-Pro
Alias tip: _ npm install --global splash-cli
/Users/alec/.nvm/versions/node/v8.9.0/bin/splash -> /Users/alec/.nvm/versions/node/v8.9.0/lib/node_modules/splash-cli/bin/index.js

> fsevents@1.1.3 install /Users/alec/.nvm/versions/node/v8.9.0/lib/node_modules/splash-cli/node_modules/fsevents
> node install

[fsevents] Success: "/Users/alec/.nvm/versions/node/v8.9.0/lib/node_modules/splash-cli/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
+ splash-cli@2.7.1
added 449 packages in 14.921s
```

`splash` command then fails with:

```sh
~ » splash                                                                                                                             alec@Alecs-MacBook-Pro
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1186:7)
    at Function.sync (/Users/alec/.nvm/versions/node/v8.9.0/lib/node_modules/splash-cli/node_modules/mkdirp/index.js:68:14)
    at client (/Users/alec/.nvm/versions/node/v8.9.0/lib/node_modules/splash-cli/client.js:98:10)
    at Object.<anonymous> (/Users/alec/.nvm/versions/node/v8.9.0/lib/node_modules/splash-cli/bin/index.js:61:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by Rawnly** [comment]
Should been fixed in the latest commit. Can you try to do the following steps?

- Clone this repo
- Run `yarn install` or `npm install`
- Run `npm start`

**Comment by AlecRust** [comment]
On 9.0.0:

```sh
~/projects/personal/3rd-party/splash-cli(node>=8) » npm i                                                                              alec@Alecs-MacBook-Pro

> fsevents@1.1.2 install /Users/alec/projects/personal/3rd-party/splash-cli/node_modules/fsevents
> node install

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-node-v59-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and node@9.0.0 (node-v59 ABI) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
In file included from ../../nan/nan.h:192:
../../nan/nan_maybe_43_inl.h:112:15: warning: 'ForceSet' is deprecated [-Wdeprecated-declarations]
  return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
              ^
/Users/alec/.node-gyp/9.0.0/include/node/v8.h:3114:3: note: 'ForceSet' has been explicitly marked deprecated here
  V8_DEPRECATED("Use CreateDataProperty / DefineOwnProperty",
  ^
/Users/alec/.node-gyp/9.0.0/include/node/v8config.h:321:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
1 warning generated.
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/alec/projects/personal/3rd-party/splash-cli/node_modules/fsevents/lib/binding/Release/node-v59-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
added 729 packages in 25.488s
------------------------------------------------------------
```

On 8.8.0 `npm i` succeeded.

**Comment by Rawnly** [comment]
Ok thank you, in the evening i'll release a new update for <code> node 8.x </code>. I think that on node <code>9.x</code> is a dependency (*fsevents*) issue, not a **splash-cli** issue.

However I'll try to investigate..

**Comment by Rawnly** [comment]
I had no problems to do a fresh install on node 9.0.0..

![screen shot 2017-11-27 at 09 24 33](https://user-images.githubusercontent.com/16429579/33257114-42e64908-d355-11e7-8bdd-cbb7959e76e6.png)

**Comment by Rawnly** [comment]
No updates.
