### ISSUE TITLE
CERT_HAS_EXPIRED analytics.splash-cli.app

### ISSUE THREAD

**Issue by MarcHagen** [splash-cli/splash-cli#52]
#### Basic informations
- **Splash CLI** version: `3.4.0`
- Node version: `v8.16.0`
- Your OS: **Win10 Pro**

#### Before you go
- [x] I've read the [FAQ](https://github.com/splash-cli/splash-cli/blob/master/FAQ.md) section.
- [x] I've the latest version of **Splash CLI installed**
- [x] I've searched other issues like mine but I haven't found a solution.

# The ISSUE

**To Reproduce**
1. Run `splash`

**Expected behavior**

**Console Output**

```
OOps! We got an error!

Please report it: on GitHub (https://github.com/splash-cli/splash-cli/issues)

Splash Error:
× { RequestError: certificate has expired
    at ClientRequest.req.once.err (C:\Users\Marc\AppData\Local\Yarn\Data\global\node_modules\got\index.js:182:22)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
  name: 'RequestError',
  code: 'CERT_HAS_EXPIRED',
  host: 'analytics.splash-cli.app',
  hostname: 'analytics.splash-cli.app',
  method: 'POST',
  path: '/api/users',
  protocol: 'https:',
  url: 'https://analytics.splash-cli.app/api/users' }

```

**Comment by Rawnly** [comment]
Sorry I forgot to renew the certificate... should have been solved
