### ISSUE TITLE
splash settings get : Reading Token Fails

### ISSUE THREAD

**Issue by lalitaalaalitah** [splash-cli/splash-cli#54]
#### Basic informations
- **Splash CLI** version: `3.4.0`
- Node version: `12.8.0`
- Your OS: **mac OS 10.14.6**

#### Before you go
- [Yes ] I've read the [FAQ](https://github.com/splash-cli/splash-cli/blob/master/FAQ.md) section.
- [Yes] I've the latest version of **Splash CLI installed**
- [Yes] I've searched other issues like mine but I haven't found a solution.

# The ISSUE
Can't get settings

**To Reproduce**
1. Run `splash settings get`

**Expected behavior**
I was expecting display for current settings which are set by `splash settings set'.

**Console Output**

```
TypeError: Cannot read property 'token' of undefined
    at Object._callee2$ (/usr/local/lib/node_modules/splash-cli/build/commands/settings.js:116:70)
    at tryCatch (/usr/local/lib/node_modules/splash-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/splash-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:296:22)
    at Generator.prototype.<computed> [as next] (/usr/local/lib/node_modules/splash-cli/node_modules/babel-runtime/node_modules/regenerator-runtime/runtime.js:114:21)
    at step (/usr/local/lib/node_modules/splash-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/splash-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:35:14
    at new Promise (<anonymous>)
    at new F (/usr/local/lib/node_modules/splash-cli/node_modules/core-js/library/modules/_export.js:36:28)
    at Object.<anonymous> (/usr/local/lib/node_modules/splash-cli/node_modules/babel-runtime/helpers/asyncToGenerator.js:14:12)
    at Object.settings (/usr/local/lib/node_modules/splash-cli/build/commands/settings.js:310:15)
```
I've tried to unisntall and reinstall node, npm and splash-cli. Nothing works.

**Comment by Rawnly** [comment]
I think that this might be related to #53. I'll investigate, thanks for reporting

**Comment by Rawnly** [comment]
Can you try the new beta? 

To install:
```sh
	$ npm i -g splash-cli@3.4.2 beta
``

**Comment by lalitaalaalitah** [comment]
Tried the new beta on a clean and new system. Still getting:
`✖ GotError [HTTPError]: Response code 401 (Unauthorized)
    at /usr/local/lib/node_modules/splash-cli/node_modules/got/index.js:386:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  name: 'HTTPError',
  host: 'api.unsplash.com',
  hostname: 'api.unsplash.com',
  method: 'GET',
  path: '/photos/random?client_id=a70f2ffae3634a7bbb5b3f94998e49ccb2e85922fa3215ccb61e022cf57ca72c&count=1&featured=false',
  protocol: 'https:',
  url: 'https://api.unsplash.com/photos/random?client_id=a70f2ffae3634a7bbb5b3f94998e49ccb2e85922fa3215ccb61e022cf57ca72c&count=1&featured=false',
  statusCode: 401,
  statusMessage: 'Unauthorized',
  headers: {
    server: 'Cowboy',
    'content-type': 'application/json',
    'access-control-allow-origin': '*',
    'access-control-request-method': '*',
    'access-control-allow-headers': '*',
    'access-control-expose-headers': 'Link,X-Total,X-Per-Page,X-RateLimit-Limit,X-RateLimit-Remaining',
    'cache-control': 'no-cache',
    'x-request-id': 'a7fa1f4f-b981-47fc-b9fb-f9be8e8a0178',
    'x-runtime': '0.013547',
    'strict-transport-security': 'max-age=31536000; includeSubDomains',
    via: '1.1 vegur, 1.1 varnish, 1.1 varnish',
    'accept-ranges': 'bytes, bytes, bytes, bytes',
    'content-length': '55',
    date: 'Sun, 22 Sep 2019 12:43:01 GMT',
    connection: 'close',
    'x-served-by': 'cache-iad2128-IAD, cache-bom18222-BOM',
    'x-cache': 'MISS, MISS',
    'x-cache-hits': '0, 0',
    'x-timer': 'S1569156182.576124,VS0,VE257',
    vary: 'Origin, Authorization'
  }
}
✖ Unable to connect.`
