### ISSUE TITLE
certificate has expired when option --day is used

### ISSUE THREAD

**Issue by reaseno** [splash-cli/splash-cli#57]
× { RequestError: certificate has expired
    at ClientRequest.req.once.err (C:\Users\%\AppData\Roaming\npm\node_modules\splash-cli\node_modules\got\index.js:182:22)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at TLSSocket.socketErrorListener (_http_client.js:392:9)
    at TLSSocket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'RequestError',
  code: 'CERT_HAS_EXPIRED',
  host: 'lambda.splash-cli.app',
  hostname: 'lambda.splash-cli.app',
  method: 'GET',
  path: '/',
  protocol: 'https:',
  url: 'https://lambda.splash-cli.app/' }
× Unable to connect.

**Comment by Rawnly** [comment]
Fixed, it was a problem with the SSL Certificate on the server.

**Comment by reaseno** [comment]
Thank you for the fast fixing.
Why is an additional server needed?

**Comment by Rawnly** [comment]
Because to get the photo of the day unload doesn’t provide any api endpoint.. so I made a script that scrapes their homepage ad get there if of the photo ✌️

**Comment by reaseno** [comment]
Can the method be added to splash-cli? Would reduce dependencies.

**Comment by Rawnly** [comment]
Yes, originally it was. But it was also slower.. the server doesn't scrape every time you ask it the new ID but just once every 6 hours ( if i remember right )

**Comment by reaseno** [comment]
Ah, I thought I read about pic of the day cache in the settings, too.
Thanks for the explanation 👍
