### ISSUE TITLE
Splash command not working

### ISSUE THREAD

**Issue by AlecRust** [splash-cli/splash-cli#69]
#### Basic informations
- **Splash CLI** version: `3.4.11`
- Node version: `13.11.0`
- Your OS: **macOS 10.15.4**

#### Before you go
- [x] I've read the [FAQ](https://github.com/splash-cli/splash-cli/blob/master/FAQ.md) section.
- [x] I've the latest version of **Splash CLI installed**
- [x] I've searched other issues like mine but I haven't found a solution.

# The ISSUE
The following command fails.

**To Reproduce**
1. Run `splash --quiet --collection editorial`

**Expected behavior**
Splash sets a new wallpaper.

**Console Output**

```sh
OOps! We got an error!

Please report it: on GitHub

Splash Error:


✖ GotError [HTTPError]: Response code 400 (Bad Request)
    at /Users/alec/.nvm/versions/node/v13.11.0/lib/node_modules/splash-cli/node_modules/got/index.js:386:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'HTTPError',
  host: 'sentry.io',
  hostname: 'sentry.io',
  method: 'POST',
? Error caught. Would you like to send some feedback? (Y/n)
```

**Comment by Rawnly** [comment]
Hi @AlecRust does this still happen? I cannot reproduce the bug.

**Comment by AlecRust** [comment]
Yup, still get this with that command. Have submitted a report via:

```sh
OOps! We got an error!

Please report it: on GitHub

Splash Error:


✖ GotError [HTTPError]: Response code 400 (Bad Request)
    at /Users/alec/.nvm/versions/node/v13.11.0/lib/node_modules/splash-cli/node_modules/got/index.js:386:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'HTTPError',
  host: 'sentry.io',
  hostname: 'sentry.io',
  method: 'POST',
  path: '/api/0/projects/federico-vitale/splash-cli/user-feedback/',
  protocol: 'https:',
  url: 'https://sentry.io/api/0/projects/federico-vitale/splash-cli/user-feedback/',
  statusCode: 400,
  statusMessage: 'Bad Request',
  headers: {
    server: 'nginx',
    date: 'Thu, 21 May 2020 14:09:52 GMT',
    'content-type': 'application/json',
    'content-length': '45',
    connection: 'close',
    'access-control-allow-headers': 'X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding',
    'x-content-type-options': 'nosniff',
    'content-language': 'en',
    'access-control-expose-headers': 'X-Sentry-Error, Retry-After',
    vary: 'Accept-Language, Cookie',
    'x-xss-protection': '1; mode=block',
    allow: 'GET, POST, HEAD, OPTIONS',
    'access-control-allow-origin': '*',
    'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS',
    'x-frame-options': 'deny',
    'x-served-by': 'web-c401c6a4',
    'strict-transport-security': 'max-age=31536000; includeSubDomains; preload'
  }
}
```

**Comment by Rawnly** [comment]
Can you try re-installing the CLI? It doesn't seem a splash-cli issue, I use Sentry library to send reports.. 🤔

**Comment by AlecRust** [comment]
After I run `npm i -g splash-cli` which updates it, and then run:

```sh
splash --quiet --collection editorial
```

An error occurs, which is caught by Sentry and clears my terminal:

```sh
? Error caught. Would you like to send some feedback?
```

**Comment by Rawnly** [comment]
I'll try updating the SDK to `v5.15.5` looks like something has changed..

**Comment by AlecRust** [comment]
Which SDK?

**Comment by AlecRust** [comment]
Not sure what changed on my system but this seems to be working again.
